---
- hosts: all
  tasks:
    - name: export settings
      routeros_command:
        commands: "/{{ item }} export terse file={{ item }}-sync.cfg"
      with_items: "{{ settings_list }}"
    - name: copy ppp script
      net_get:
        protocol: scp
        src: "{{ item }}-sync.cfg.rsc"
        dest: "/data/git/routeros/{{ group_names[0] }}/{{ item }}-sync.cfg.rsc"
      with_items: "{{ settings_list }}"
    - name: Remove file
      routeros_command:
        commands: "/file remove [find name~'-sync.cfg.rsc']"
    - name: Remove lines
      lineinfile:
        dest: "/data/git/routeros/{{ group_names[0] }}/{{ item }}-sync.cfg.rsc"
        regexp: '^#.*\r\n'
        state: absent
      with_items: "{{ settings_list }}"
...
